add docker
a-omori-yumemi/YumetterAPI pull request #4
Opened 2021-10-14 02:29 UTC by a-omori-yumemi

## 実装内容
Docker sqlxで繋いでINSERT,SELECTまで確認できた

## レビュー優先度
- [ ] すぐに見てもらいたい（hotfixなど） 🚀
- [ ] 今日中に見てもらいたい 🚗
- [ ] 今日〜明日中で見てもらいたい 🚶
- [ ] 数日以内で見てもらいたい 🐢

## レビュー観点

- 

## 変更の種類

- [ ] 新機能
- [ ] バグ修正
- [ ] リファクタリング
- [ ] ドキュメント作成・更新
- [ ] その他

## チェックリスト

- ドキュメントの作成あるいは更新を行いましたか？
  - [ ] 作成・更新した
  - [ ] 作成・更新していない

- テストを作成あるいは更新しましたか？
  - [ ] 作成・更新した
  - [ ] 作成・更新していない

## その他

2021-10-14 02:38 UTC, ikasam commented on docker-compose.yml
> +    build: docker-db
![suggest](https://img.shields.io/badge/review-suggest-success.svg)

MySQL のコンテナに何か手を入れるとかがなければ、`Dockerfile` 書かずに素のまま `image` を使うとよいです

```suggestion
    image: mysql:5.7
```

2021-10-14 02:40 UTC, siketyan requested changes

2021-10-14 02:40 UTC, siketyan commented on docker-compose.yml
> +      DB_DATABSE: yumetter_db
```suggestion
      DB_DATABASE: yumetter_db
```

2021-10-14 02:47 UTC, a-omori-yumemi commented on docker-compose.yml
> +      DB_DATABSE: yumetter_db
なぜこれで動いていたのか

2021-10-14 03:00 UTC, foolishell commented on docker-compose.yml
> +      DB_DATABSE: yumetter_db
Golangのコードの方も`DATABSE`になってるね

2021-10-14 03:01 UTC, foolishell commented on main.go
> +		Database: os.Getenv("DB_DATABSE"),
here
```suggestion
		Database: os.Getenv("DB_DATABASE"),
```

2021-10-15 00:57 UTC, siketyan approved these changes

2021-10-15 00:57 UTC, siketyan commented on Dockerfile
> +FROM scratch AS prod
デフォルトで使うイメージになるのでこれは名前付きじゃなくてよいかも

2021-10-15 01:47 UTC, merged